function tuneDB = TuneDB_default(cfg)
tuneDB = struct();

PID = struct( ...
    "Kp",50.0,"Ki",0.0,"Kd",0.2, ...
    "intMax",10.0, ...
    "outMaxDeg",45.0, ...
    "rateLimitDegPerS", inf, ...
    "deadband", cfg.line.deadbandPos, ...
    "dAlpha", 1.0 );

ONOFF = struct( ...
    "centerU16", cfg.steer.centerU16, ...
    "leftMaxU16", cfg.steer.minU16, ...
    "rightMaxU16", cfg.steer.maxU16, ...
    "threshold", 0.15, ...
    "hysteresis", 0.03, ...
    "holdFrames", uint16(1), ...
    "lostLineStrategy", "HOLD" );

conds = ["NORMAL","UNSTABLE","LOST","SPECIAL"];
for k=1:numel(conds)
    c = conds(k);
    tuneDB.global.PID.(c) = PID;
    tuneDB.global.ONOFF.(c) = ONOFF;
end

% Example road entries (optional)
tuneDB.road = struct([]);
end
