function st = makeAppStateDefault(cfg) %#ok<INUSD>

    st = struct();

    st.run = struct( ...
        "enabled", false, ...
        "stopRequest", false, ...
        "mode", "AUTO", ...
        "manual", struct("enable",false,"speedU8",uint8(0),"angleU16",uint16(0),"cmd",uint8(hex2dec('F1'))) );

    st.control = struct( ...
        "type", "PID", ...
        "enable", true );

    st.road = struct( ...
        "stateId", uint16(0), ...
        "forceState", false, ...
        "forcedStateId", uint16(0) );

    st.tune = struct( ...
        "useGlobal", true );

    st.condition = struct( ...
        "line", "OK", ...
        "stability", "NORMAL", ...
        "road", "NORMAL" );
end
