function rt = makeRuntimeFrame()
    rt = struct( ...
        "t", 0.0, ...
        "meas", struct("lineRaw",[],"ultra",[],"mpu",[],"encCount",[],"encSpeed",[]), ...
        "proc", struct("lineNorm",[],"mask",[],"error",0.0), ...
        "logic", struct("roadId",uint16(0),"action","","note",""), ...
        "cmd", struct("cmd",uint8(0),"speedU8",uint8(0),"angleU16",uint16(0)) );
end
