road(1) = struct('index',1, ...
                 ...% Road general information
                 'type','line', ...
                 ...% Motion profile
                 'length',300, ...
                 'tDec',0.5, ...
                 'vSteady',150, ...
                 'tAcc',0.5, ... % Encoder pulse
                 ...% Robot control range
                 'offsetAngle',75, ...
                 'addAngleMax',8, ...
                 'addAngleMin',8, ...
                 ...% On/Off control's parameters
                 'OnOffMax',10, ...
                 'OnOffMin',-10, ...
                 ...% PID control's parameters
                 'Kp',5.0, ...
                 'Ki',0.0,  ...
                 'Kd',0.4,  ...
                 ...% Information
                 'offRoad',true, ...
                 'counter',0);