robot = struct( ...
    ... % Mechanical / steering limits
    'centerAngle',      90, ...
    'MaxAngle',         110, ...
    'MinAngle',         60, ...
    ... % Motor command limits
    'minPWM',           0, ...      % Điền sau khi đo deadzone động cơ
    'maxPWM',           255, ...
    'maxSpeed',         0.8, ...    % m/s (tham chiếu)
    ... % Network connection
    'network',          'bt', ...
    'networName',       'Behind the scream', ...  % giữ nguyên tên field như bạn đang dùng
    'networkPort',      1, ...
    ... % Line sensor calibration / normalization
    'lineBlack',        [5.860  5.850  5.900  5.860  5.520], ...
    'lineLight',        [38.080 45.600 46.060 41.780 39.250], ...
    'lineUseNormalize', true, ...   % dùng công thức (x - xmin)/(xmax - xmin)
    'lineYmin',         0.0, ...
    'lineYmax',         1.0, ...
    'lineThresh',       0.5, ...    % ngưỡng phân biệt trắng/đen sau normalize
    'lineSatLow',       0.0, ...    % saturation sau normalize (clamp)
    'lineSatHigh',      1.0, ...
    ... % Ultrasonic calibration
    'ultraOffset',      0, ...
    'ultraScale',       1, ...
    ... % Encoder / kinematics (điền đúng theo phần cứng thực)
    'gearbox',          1/12, ...
    'wheelDiameter',    0.072, ...  % [m] cần kiểm tra lại
    'ticksPerRev',      512, ...    % xung encoder / vòng (sau hộp số)
    'trackWidth',       0.21, ...   % [m] khoảng cách hai bánh
    ... % Global PID for steering (nếu không dùng road-dependent PID)
    'Kp',               5.0, ...
    'Ki',               0.0, ...
    'Kd',               0.2, ...
    'Ts',               0.025, ...  % [s] thời gian lấy mẫu 40 Hz
    ... % PID extra params – anti-windup, filter
    'useAntiWindup',    true, ...
    'Imin',             -50, ...    % giới hạn tích phân (điền lại sau khi thử)
    'Imax',             50, ...
    'KdFilterN',        10, ...     % hệ số lọc đạo hàm (bộ lọc 1st-order)
    'outputMin',        -30, ...    % giới hạn lệnh PID (độ lệch góc)
    'outputMax',        30, ...
    ... % Default steering angles (khi điều khiển On/Off / ra lệnh trực tiếp)
    'defaultAngle',     90, ...
    'addLeftAngle',     100, ...
    'addRightAngle',    80, ...
    ... % Velocity estimation / filtering
    'velUseEncoder',    true, ...
    'velSampleTime',    0.05, ...   % [s] cho ước lượng vận tốc
    'velLPF_fc',        5, ...      % [Hz] tần số cắt lọc thông thấp vận tốc
    ... % MPU6050 / IMU parameters
    'mpuEnable',        true, ...
    'mpuYawOffset',     0.0, ...    % offset góc yaw sau khi calib
    'mpuGyroScale',     1.0, ...    % hệ số scale gyro (rad/s per LSB) điền theo datasheet
    'mpuAccScale',      1.0, ...    % hệ số scale accel (m/s^2 per LSB)
    'mpuLPF_fc',        10, ...     % [Hz] low-pass cho tín hiệu yaw
    'useComplementary', true, ...
    'compAlpha',        0.98, ...   % tham số bộ lọc bổ sung angle = α*(angle+gyro*dt)+(1-α)*accAngle
    ... % Flags cho chế độ điều khiển
    'usePID',           true, ...   % true: PID, false: On/Off
    'failSafeTimeout',  0.5, ...    % [s] mất gói lệnh thì dừng
    'debugMode',        false ...   % bật/tắt debug
);
